### ISSUE TITLE
Allow evaluation of resources including count and for_each

### ISSUE THREAD

**Issue by janritter** [terraform-linters/tflint-plugin-sdk#151]
We have created an internal tflint plugin which checks checks for our naming convention on all resources in a state. With the update to the new v10 plugin sdk I noticed that some resources are skipped when they include for example a count.

In the following example only the aws_eip.two is evaluated:

```hcl
variable "test" {
  type = number
}

resource "aws_eip" "one" {
  count    = var.test
  vpc      = true
  instance = "i-123456789"
}

resource "aws_eip" "two" {
  vpc      = true
  instance = "i-123456789"
}
```

aws_eip.one is skipped with the following warning:
```
16:40:36 runner.go:317: [WARN] Skip walking `aws_eip.one` because it may not be created
```

I'm getting a list of resources via GetModuleContent, this list doesn't include the skipped resources:
```go
func (r *TerraformMyRule) Check(runner tflint.Runner) error {
	content, err := runner.GetModuleContent(&hclext.BodySchema{
		Blocks: []hclext.BlockSchema{
			{
				Type:       "resource",
				LabelNames: []string{"type", "name"},
			},
		},
	}, nil)
```

Is there any option to disable this skipping behaviour for specific plugins?

Similar issue in tflint: https://github.com/terraform-linters/tflint/issues/1068

**Comment by janritter** [comment]
Interesting, then I just noticed this by testing the 0.10 update 😄 

Adding an option to `GetModuleContent` sounds like a good idea.

**Comment by janritter** [comment]
I updated to the plugin-sdk version 0.11.0 including the new GetModuleContent option.
With the following code snippet, I still get the "Skip walking `aws_eip.one` because it may not be created` warning":
```golang
	content, err := runner.GetModuleContent(
		&hclext.BodySchema{
			Blocks: []hclext.BlockSchema{
				{
					Type:       "resource",
					LabelNames: []string{"type", "name"},
				},
			},
		},
		&tflint.GetModuleContentOption{
			IncludeNotCreated: true,
		},
	)
```

**Comment by wata727** [comment]
Are you using it with TFLint v0.36.2? In v0.35, this option is simply ignored.

**Comment by janritter** [comment]
Thanks, my TFLint version was outdated
