### ISSUE TITLE
Question: How to get Expr as raw string without evaluating it?

### ISSUE THREAD

**Issue by Vince-Chenal** [terraform-linters/tflint-plugin-sdk#212]
Hey,

I'm struggling with the sdk to get an Expr as a raw string without evaluating it.

Here's an example:
I want to make sure that all the vault providers are configured the right way, it should look like:

```
provider "vault" {
  address = var.vault_addr
}
```
or

```
provider "vault" {
  address = module.vault_finder.address
}
```

But I'm struggling to get `var.vault_addr` or `module.vault_finder.address`

I was able to get a splitted view of the Expr by iterating along the Traversers but it's clearly not convenient...
```
func AddressFieldDefinedInVaultProvider(attributes hclext.Attributes) bool {
	for _, v := range attributes {
		for _, v1 := range v.Expr.Variables() {
			for _, v2 := range v1 {
				switch v2.(type) {
				case hcl.TraverseAttr:
					logger.Debug(v2.(hcl.TraverseAttr).Name)
				case hcl.TraverseRoot:
					logger.Debug(v2.(hcl.TraverseRoot).Name)
				}
			}
		}
	}
	return false
}

```

Am I missing another obvious solution?

**Comment by wata727** [comment]
You can get the raw string by using `GetFile()` API.

```go
file, _ := c.GetFile(expr.Range().Filename)
expr.Range().SliceBytes(file.Bytes) // =>  expr as []byte
```

https://pkg.go.dev/github.com/terraform-linters/tflint-plugin-sdk@v0.14.0/tflint#Runner

Alternatively, you can use `lang.ReferencesInExpr` to get named values in the expr.
https://pkg.go.dev/github.com/terraform-linters/tflint-plugin-sdk@v0.14.0/terraform/lang#ReferencesInExpr

**Comment by Vince-Chenal** [comment]
Thanks for your answer, I'll try this option :pray:
