### ISSUE TITLE
runner.GetModulePath failing to provide any path

### ISSUE THREAD

**Issue by yashg-ti** [terraform-linters/tflint-plugin-sdk#259]
Issue: 
From what I've come across about this method, it should return the path of the child module from the terraform tree. However, it's returning nil when using it with the runner of any module.

Description: 
path of childmodule is ```./auth-module/main.tf```
commands I ran is 
```terraform init``` only in root
```terraform apply``` only in root
```path/to/tflint --recursive --config path/to/.tflint.hcl --module --disable-rule=module_source``` in root
version of tflint 0.44.1
.tflint.hcl file is as follows
	config {
		disabled_by_default = true
	}
	plugin "developer"{
		enabled = true
	}
	rule "flag_recommend"{
		enabled=true
	}

tflint ruleset plugin link: 
https://github.com/trilogy-group/tflint-ruleset-template 
The ruleset basically retrieves 2 files from env, and emits issues on resources blocks based on info in the 2 files.
I ran runner.GetModulePath as the first thing in check function, and it returned null for all tf file templates (including child).

Expected outcome: 
when accessing module path using runner.GetModulePath inside the check function of my tflint-ruleset-plugin, it should return some information of the path to my childmodule, i.e., the terraform file inside ./auth-module/main.tf directory.

A few concerns regarding this issue to give a direction to issue elaboration : 
Is it correct, that this method will provide path corresponding to the terraform project tree, and return a string containing ancestors? 
How exactly is that information obtained by tflint, is there a special way of processing the terraform project for enabling tflint to generate that tree. 
In code I saw, TFConfig.path to be containing this value, where is it getting that value from, tf file path specified in command?

**Comment by yashg-ti** [comment]
@wata727  Right, thanks alot for the clarification! Let me know if I got it right.
--module flag allows a recursvie inspection, but only to one level w.r.t. to root file that we called tflint for. This inspection is exactly same as what tflint would do, i.e., creates another runner for child modules and tries to emit issues based on the custom rules(plugin). But the catch here is, out of the emitted issues, only those will be accepted/ get relayed back to the root file's module call block, which are corresponding to a variable passed in that call/ specified in that module block in the root file. Other's get ignored, and hence as a final result, we get the lintings corresponding to the root file's resource block and the module blocks (if any, due to that flag). 
Now getmodulepath, will return the child module path in that 1 level recursion and that path can be used there. So get module path can only have, at max, a slice of 2 values.

Now coming to our application, to summarize, our application gets a map of [arn -> lintings /new attributes for resources] from an external api. What we have in our application, is another map of [resourceBlockAddressInTFcode -> arn]. And thus eventually, we have [resourceBlockAddressInTFcode -> lintings]. The resource block addresss is basically: FilePath-resourceName. Incusion of FilePath ensures our address is going to be unique for each resource block, in our entire terraform project. 
Now for emitting issues from the plugin, we needed to know the filepath that gets passed with the tflint command, after getting resources-data from the tflint server. We needed the filepath to be able to regenerate that resourceBlockAddress for the current resource, and emmit the corresponding lintings from the map.
That filepath is basically where issues are going to be emitted, so we could access it using the Range section of the resource schema, the section which contains the resource block coordinates.

We were under the impression, that getModulePath would just return some similar path, that we could use here. Hence, raised the issue. But now it's clear that's not the case.
Please let me know if the current understanding above is accurate, and any insights (if any) that you'd like to share after knowing our application/ use-case.

**Comment by yashg-ti** [comment]
Also, there seems to be problem with emitting issue for ```ebs_block_device/ root_block_device``` using ```--module flag```.
`resource "aws_instance" "app-server" {

  ami           = "ami-09d56f8956ab235b3"
  instance_type = var.web_instance_type
  tags = {
    created_for                 = "cloudfix-linter demo"
    Owner                       = "ankush.pandey@trilogy.com"
  }
   root_block_device {
    volume_type           = "gp2"
    volume_size           = "8"
    delete_on_termination = true
  }
    ebs_block_device {
    device_name           = "xvda"
    volume_type           = var.ebs_device_type
    volume_size           = "8"
    delete_on_termination = false
  }
}`

This is my code from a chile module. Using var.ebs_device_type, ideally the issue should be emitted in the module call block in the root file, where the value for this var is passed (using --module flag). However, it returns an error ```Invalid reference; A reference to a resource type must be followed by at least one attribute access, specifying the resource name.``` , marking the ebs_block_device in my child module file. 
It seems to me the logic for --module flag is expecting me to emit the issue in a different way that it can get relayed back to the module call block. I emit it using- ```Block.Attribute["x"].Expr.Range()``` , works out everytime, except this one.

**Comment by wata727** [comment]
> --module flag allows a recursvie inspection, but only to one level

No, there is no limit to the depth of child modules in module inspection. So the `GetModulePath` can return a slice with more than two values.

Thanks for sharing your use case.
From what I've read, it seems that the requirements can be met without the module's relative path on the file system.
If there's a requirement that the current API can't meet, please let me know with a concrete example.

> Also, there seems to be a problem with emitting issue for ebs_block_device/ root_block_device of child module, using --module flag.

This is another issue and we do not recommend discussing it in this issue.
However, based on the error message, it seems to be parsing an invalid expression and not an issue with TFLint.
Please open a new issue with a minimal repro if you can demonstrate that it's a TFLint issue.

**Comment by yashg-ti** [comment]
Thanks alot for the information! 
GetModulePath is working fine, and am going to close this issue now.

Yes, our application is functional using the current API, except this one error when using --module flag.

Sure, will raise another issue on that in some time, with relevant information.
