### ISSUE TITLE
provide ability to retrieve all resources of a type

### ISSUE THREAD

**Issue by iwarapter** [terraform-linters/tflint-plugin-sdk#30]
I'm looking to implement a rule for a custom provider but i need to be able to identify all the resources of a given type for one of my checks. I know the core plugins can directly iterate over the `ManagedResources` https://github.com/terraform-linters/tflint/blob/99035e1be1b0c5158999c3e9185ab419fe03878d/rules/terraformrules/terraform_deprecated_interpolation.go#L45 is this something that could be exposed in the sdk?

EDIT:
I have done tests using the `runner.WalkResourceAttributes` to iterate over all of the resources but all the errors get raised on the attribute i search for not the resource itself - which is mislead in my case.

A `WalkResource` would work I believe?

**Comment by wata727** [comment]
Hi @iwarapter,

If you don't mind, please let me know what kind of rule you are trying to write. I think in most cases you can write rules with `WalkResourceAttributes` (and `WalkResourceBlocks`).

**Comment by iwarapter** [comment]
Hi @wata727,

I'm looking to write a rule that detects duplicate instances of a resource for an instance of a provider as i have resources which are singletons and this cannot be enforced with terraform atm: https://discuss.hashicorp.com/t/singleton-resource/9869

So ultimately i just need to see if their is more than one of resource X for any instances of the provider.

```hcl
resource "pingaccess_pingfederate_runtime" "foo" {
    issuer = "https://foo"
}

# non compliant
resource "pingaccess_pingfederate_runtime" "bar" {
    issuer = "https://bar"
}
```

**Comment by wata727** [comment]
I see, thank you. I understand this use case.

Unfortunately, there are currently no APIs for this purpose, but I would like to consider adding an API like `WalkResources`.

**Comment by iwarapter** [comment]
Hi @wata727 ,

I was just having a look at what it would take for me todo this, i think we'd need to extend the server to return the resources for the plugins:
https://github.com/terraform-linters/tflint/blob/81faa69e3e5315d0a0f89b7e6623b4f94cd01785/plugin/server.go
Then add to the client the new `WalkResources`:
https://github.com/terraform-linters/tflint-plugin-sdk/blob/master/tflint/client.go

Is their anything else? If i'm om the right track i'll try add a PR for this.

**Comment by wata727** [comment]
Great, that's exactly what we need.

But the difficult problem is how to transfer the `github.com/hashicorp/terraform/configs.Resource` via RPC. I don't want to add a dependency on Terraform to our SDK, so you'll need to define another equivalent struct yourself.

Also, this resource contains `hcl.Body` and `hcl.Expression`, so it's probably better to wait for support to be able to transfer blocks with RPC (this work is currently in progress but not yet completed)

**Comment by iwarapter** [comment]
Yeah, i had a quick look at the `configs.Resource` and was looking at a simpler transfer struct we could use:
```golang
// Resource is an intermediate representation of configs.Resource.
type Resource struct {
	Name string
	Type string

	DeclRange hcl.Range
	TypeRange hcl.Range
}
```
Given that most checks will use either the attribute/block walkers I dont immediately see a need to send the complete original resource (we can always extend it later).

I added an example here: https://github.com/iwarapter/tflint-plugin-sdk/commit/7c3de4754d8de7fffc16a7b7793794259641f9aa

And corresponding tflint:
https://github.com/iwarapter/tflint/commit/7fd7c53a8d71b2fe75c51e5eb8696c8213de499f

I have only written some simple unit tests atm. Thoughts?

**Comment by wata727** [comment]
Looks good! it's a good start to support resources.
Could you open a pull request?

**Comment by iwarapter** [comment]
PR is open, was having a look at the https://github.com/terraform-linters/tflint-plugin-sdk/tree/master/helper and trying to think about the best way to implement the `WalkResources` for the test helper.

**Comment by wata727** [comment]
Ah, good point. I forgot to add this when adding `WalkResourceBlocks` API...
Probably it will be an implementation that takes a block with `PartialContent` and passes it to the walker. The following is helpful:
https://github.com/terraform-linters/tflint-plugin-sdk/blob/56764093bb1a3e81fadd52699691849f60af831c/helper/runner.go#L21-L33

The following is a reference for the process of building `configs.Resource` from the block:
https://github.com/hashicorp/terraform/blob/bc386234d528747ad244574f72f1fc30a486d5c2/configs/resource.go#L80-L89

**Comment by iwarapter** [comment]
Yeah i was just checking with the tflint changes I was creating the correct ranges in the new `Resource` struct.

**Comment by iwarapter** [comment]
Do we need anything other than the tflint changes merged to close this?

**Comment by wata727** [comment]
Don't worry, you should have done all we need to do. Thank you again!
I plan to release tflint-plugin-sdk v0.2.0 in the near future. Please wait until then.
