### ISSUE TITLE
Support JSON configuration syntax

### ISSUE THREAD

**Issue by wata727** [terraform-linters/tflint-plugin-sdk#32]
Currently, the `WalkResourceAttributes` and `WalkResourceBlocks` API don't support JSON configuration syntax. To support this, the following features need to be merged in the HCL. This is a tracking issue.

https://github.com/hashicorp/hcl/pull/381
https://github.com/hashicorp/hcl/pull/389

**Comment by freddd** [comment]
Hi @wata727 - I'm sure you are already aware but in case you aren't, they released a new version of HCL a few days ago: https://github.com/hashicorp/hcl/releases/tag/v2.7.0

**Comment by bendrucker** [comment]
See #69 🙂
