### ISSUE TITLE
Access to Backend configuration

### ISSUE THREAD

**Issue by pd** [terraform-linters/tflint-plugin-sdk#46]
At $DAYJOB, I've started writing our own ruleset to enforce some very company-specific rules. One of the most valuable is validating that our backend configurations specify the correct attributes, so we can ensure that locks are always correctly taken, the tfstate is stored in S3 at the correct location, etc. Unfortunately, the SDK currently only permits walking over resources.

I've been looking into adding support for exposing more to the SDK, but I'm not sure what the preferred approach would be. Adding a `Backend()` func to the runners seemed straightforward enough, and I managed to put together a spike of it which more or less seems to work for a test rule:

```
1 issue(s) found:
Error: remote state backend must be S3 (backend_lint_hax)
  on test/backend.tf line 2:
   2:   backend "totally_wrong" {
```

But this implementation doesn't fit in terribly well with the `WalkResourceAttributes` style functions that are currently available.

Zooming out a bit, other rules I'd like to add will want access to `ModuleCalls`, `ProviderConfigs`, etc. Is there a more general approach to this issue, something like `WalkBlocks(type string, ...)` or such? That might be pretty unwieldy on the caller's side, though.

If this seems like a reasonable feature request, I'd be happy to help with implementation if I can.

**Comment by wata727** [comment]
Hi @pd!

As you say, the `Backend` is always single, so functions like `WalkBackends` won't fit. I agree to add the `Bankend()` function to the runner.

Ideally, I would like to be able to access it with a structure similar to Terraform via a function such as `Config()`, but it seems a little difficult now. Imagine something like the following:

```go
runner.Config().Module.Backend
```

If you open a pull request, I will be happy to review it. Thanks.
